version: "3.5"
services:
  web:
    image: tableau-web-vue_v1.0.0
    build:
        context: .
        dockerfile: ./Dockerfile
    ports:
      - 8080:8081
    command: sh -c "npm install && npm run serve"
    volumes:
      - ".:/app"
    environment:
      HOST: 0.0.0.0