version: "3"
services:
  web:
    build:
        context: .
        dockerfile: ./Dockerfile
    ports:
      - 8080:8081
    command: sh -c "npm install && npm run dev"
    volumes:
      - ".:/app"
    environment:
      HOST: 0.0.0.0